In [36]:
import pandas as pd
database = pd.read_excel('database_TCC.xlsx')
database = database[['A','E','N','Rt']]
database

A  E   N     Rt
0   25  1  11  1.638
1   25  1   5  2.595
2   25  2   8  1.976
3   25  3  11  4.164
4   25  3   5  2.869
5   35  1   8  1.421
6   35  2  11  1.564
7   35  2   5  2.101
8   35  3   8  1.591
9   25  1   8  1.946
10  25  2   5  2.991
11  35  3  11  2.896

In [37]:
from sklearn.preprocessing import StandardScaler
standardscaler = StandardScaler()
standardscaler.fit(database)
data = standardscaler.transform(database)
database = pd.DataFrame(data,columns=database.columns)

In [38]:
import pickle
pickle.dump(standardscaler, open('standard_scaler_Rt.pkl','wb'))

In [39]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,max_error

def split_x_and_y(database,x,y):
  dataset_x = database[x]
  dataset_y = database[y]
  return dataset_x,dataset_y


def scores(Y_true, Y_predicted):
  r2 = r2_score(Y_true, Y_predicted)
  meansquarederror = mean_squared_error(Y_true, Y_predicted)
  meanabsoluteerror = mean_absolute_error(Y_true, Y_predicted)
  maxerror = max_error(Y_true, Y_predicted)

  print('r2:',r2,'meansquarederror:',meansquarederror,'meanabsoluteerror:',meanabsoluteerror,'maxerror:',maxerror)
  return r2,meansquarederror,meanabsoluteerror,maxerror


# Random Forest Regressor

In [42]:
# database.iloc[[0,2,4,5,7,8]]

dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=5000,random_state=100)
RFR.fit(dataset_x,dataset_y)
RFR.score(test_x,test_y)

0.3306427822593704

In [43]:
RFR.feature_importances_

array([0.21042855, 0.33216308, 0.45740836])

In [44]:
import pickle
pickle.dump(RFR, open('Random_Forest_Regressor_Rt.pkl', 'wb'))

# SVM

In [45]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn import svm

svr = svm.SVR(kernel='sigmoid',C=3,gamma='auto')

svr.fit(dataset_x,dataset_y)
svr.score(test_x,test_y)

0.4359749662202925

In [46]:
import pickle
pickle.dump(svr, open('Support_Vector_Machine_Rt.pkl', 'wb'))

# MLP

In [29]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor(max_iter=1000,random_state=100)
MLP.fit(dataset_x,dataset_y)
MLP.score(test_x,test_y)

-0.05892459425244634

In [23]:
# import pickle
# pickle.dump(MLP, open('MLP_Rt.sav', 'wb'))

# Keras

In [131]:
import tensorflow as tf
from tensorflow import keras
# from tensorflow.python.keras.layers import Dense
import pandas as pd
from tensorflow.keras import layers

import keras
from keras.models import Sequential
from keras.layers import Dense

variables,results = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')
test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

model = keras.Sequential([
  layers.Dense(32, activation='sigmoid', input_shape=[len(variables.keys())]),
  # layers.Dropout(0.2),
  layers.Dense(64, activation='relu'),
  layers.Dense(256, activation='relu'),
  # layers.Dense(32, activation='relu'),
  # layers.Dense(64, activation='relu'),
  # layers.Dropout(0.2),
  # layers.Dense(128, activation='relu'),
  # layers.Dense(64, activation='sigmoid'),
  # layers.Dense(8, activation='relu'),
  layers.Dense(1)
])

# optimizer = tf.keras.optimizers.RMSprop(0.001)

model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

model.fit(variables.values,results.values,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 371ms/step - loss: 1.2186 - accuracy: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1243 - accuracy: 0.0000e+00
Epoch 3/300
1/1 [==============================] - 0s 4ms/step - loss: 1.0651 - accuracy: 0.0000e+00
Epoch 4/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0303 - accuracy: 0.0000e+00
Epoch 5/300
1/1 [==============================] - 0s 6ms/step - loss: 1.0046 - accuracy: 0.0000e+00
Epoch 6/300
1/1 [==============================] - 0s 3ms/step - loss: 0.9759 - accuracy: 0.0000e+00
Epoch 7/300
1/1 [==============================] - 0s 3ms/step - loss: 0.9418 - accuracy: 0.0000e+00
Epoch 8/300
1/1 [==============================] - 0s 3ms/step - loss: 0.9037 - accuracy: 0.0000e+00
Epoch 9/300
1/1 [==============================] - 0s 2ms/step - loss: 0.8666 - accuracy: 0.0000e+00
Epoch 10/300
1/1 [==============================] - 0s 2ms/step - loss: 0.8326 - accuracy

In [132]:
guess = model.predict(test_x.values)
desnormalizar = test_x.copy()
desnormalizar['Rt'] = guess
desnormalizado_teste = standardscaler.inverse_transform(desnormalizar)
desnormalizado_teste

1/1 [==============================] - 0s 52ms/step


array([[25.        ,  1.        ,  8.        ,  1.85900101],
       [25.        ,  2.        ,  5.        ,  2.70135503],
       [35.        ,  3.        , 11.        ,  2.44664487]])

In [133]:
desnormalizar = test_x.copy()
desnormalizar['Rt'] = test_y
desnormalizado_resultado = standardscaler.inverse_transform(desnormalizar)
desnormalizado_resultado

array([[25.   ,  1.   ,  8.   ,  1.946],
       [25.   ,  2.   ,  5.   ,  2.991],
       [35.   ,  3.   , 11.   ,  2.896]])

In [134]:
scores(desnormalizado_resultado[:,-1],desnormalizado_teste[:,-1])

r2: 0.5607051471657352 meansquarederror: 0.09779435582178791 meanabsoluteerror: 0.27533303105076423 maxerror: 0.4493551311139612


(0.5607051471657352,
 0.09779435582178791,
 0.27533303105076423,
 0.4493551311139612)

In [136]:
model.save("keras_model_Rt.h5")