In [2]:
import pandas as pd
database = pd.read_excel('database_TCC.xlsx')
database = database[['A','E','N','Nu']]

In [3]:
from sklearn.preprocessing import StandardScaler
standardscaler = StandardScaler()
standardscaler.fit(database)
data = standardscaler.transform(database)
database = pd.DataFrame(data,columns=database.columns)

In [4]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,max_error

def split_x_and_y(database,x,y):
  dataset_x = database[x]
  dataset_y = database[y]
  return dataset_x,dataset_y


def scores(Y_true, Y_predicted):
  r2 = r2_score(Y_true, Y_predicted)
  meansquarederror = mean_squared_error(Y_true, Y_predicted)
  meanabsoluteerror = mean_absolute_error(Y_true, Y_predicted)
  maxerror = max_error(Y_true, Y_predicted)

  print('r2:',r2,'meansquarederror:',meansquarederror,'meanabsoluteerror:',meanabsoluteerror,'maxerror:',maxerror)
  return r2,meansquarederror,meanabsoluteerror,maxerror


# Random Forest Regressor

In [50]:
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')

In [51]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(dataset_x,dataset_y)

0.9671102471540665

In [52]:
# database.iloc[[0,2,4,5,7,8]]

dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(test_x,test_y)

0.8871363931506178

In [53]:
print(RFR.predict(X = test_x))
print(test_y)

[ 0.77459176  0.62905865 -1.27770633]
9     0.847698
10    0.477469
11   -1.991431
Name: Nu, dtype: float64


# SVM

In [54]:
from sklearn import svm
regr = svm.SVR()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
regr.fit(dataset_x,dataset_y)
regr.score(dataset_x,dataset_y)

0.8172304972011419

In [1]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn import svm
regr = svm.SVR()
regr.fit(dataset_x,dataset_y)
regr.score(test_x,test_y)

NameError: name 'split_x_and_y' is not defined

# Linear Regression

In [56]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
LR.fit(dataset_x,dataset_y)
LR.score(dataset_x,dataset_y)

0.8534552882348707

In [57]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(dataset_x,dataset_y)
LR.score(test_x,test_y)

0.8326467092134622

# SGD

In [58]:
from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
SGD.fit(dataset_x,dataset_y)
SGD.score(dataset_x,dataset_y)

0.8220612747160446

In [59]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
SGD.fit(dataset_x,dataset_y)
SGD.score(test_x,test_y)

0.7113566713449342

# BayesianRidge

In [60]:
from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
bayesian.fit(dataset_x,dataset_y)
bayesian.score(dataset_x,dataset_y)

0.8504968238317749

In [61]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
bayesian.fit(dataset_x,dataset_y)
bayesian.score(test_x,test_y)

0.7880374301579827

# MLP

In [62]:
from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
MLP.fit(dataset_x,dataset_y)
MLP.score(dataset_x,dataset_y)

c:\Users\vinao\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.9910063729658656

In [63]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor()
MLP.fit(dataset_x,dataset_y)
MLP.score(test_x,test_y)

0.9063360435352729

# Polynomial and Linear

In [64]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(2)
LR = LinearRegression()

dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')

dataset_x_transformed = poly.fit_transform(dataset_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(dataset_x_transformed,dataset_y)

0.9860105919141751

In [65]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(2)
LR = LinearRegression()

dataset_x_transformed = poly.fit_transform(dataset_x)
test_x_transformed = poly.fit_transform(test_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(test_x_transformed,test_y)

0.9325286588196521

# Ridge

In [23]:
from sklearn.linear_model import Ridge
ridge = Ridge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Nu')
ridge.fit(dataset_x,dataset_y)
ridge.score(dataset_x,dataset_y)

0.8489910557649081

In [24]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(dataset_x,dataset_y)
ridge.score(test_x,test_y)

0.7894379091959658

# Keras

In [5]:
variables,results = split_x_and_y(database,['A','E','N'],'Nu')
variables.values.shape

(12, 3)

In [6]:
import tensorflow as tf
from tensorflow import keras
# from tensorflow.python.keras.layers import Dense
import pandas as pd
from tensorflow.keras import layers

import keras
from keras.models import Sequential
from keras.layers import Dense

variables,results = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Nu')
test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Nu')

model = keras.Sequential([
  layers.Dense(64, activation='sigmoid', input_shape=[len(variables.keys())]),
  # layers.Dropout(0.1),
  layers.Dense(128, activation='sigmoid'),
  layers.Dense(64, activation='sigmoid'),
  layers.Dense(16, activation='sigmoid'),
  layers.Dense(8, activation='sigmoid'),
  # layers.Dense(8, activation='relu'),
  layers.Dense(1)
])

# optimizer = tf.keras.optimizers.RMSprop(0.001)

model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

model.fit(variables.values,results.values,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 481ms/step - loss: 0.8247 - accuracy: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 0.8110 - accuracy: 0.0000e+00
Epoch 3/300
1/1 [==============================] - 0s 3ms/step - loss: 0.8002 - accuracy: 0.0000e+00
Epoch 4/300
1/1 [==============================] - 0s 4ms/step - loss: 0.7922 - accuracy: 0.0000e+00
Epoch 5/300
1/1 [==============================] - 0s 4ms/step - loss: 0.7867 - accuracy: 0.0000e+00
Epoch 6/300
1/1 [==============================] - 0s 6ms/step - loss: 0.7834 - accuracy: 0.0000e+00
Epoch 7/300
1/1 [==============================] - 0s 3ms/step - loss: 0.7820 - accuracy: 0.0000e+00
Epoch 8/300
1/1 [==============================] - 0s 4ms/step - loss: 0.7820 - accuracy: 0.0000e+00
Epoch 9/300
1/1 [==============================] - 0s 5ms/step - loss: 0.7827 - accuracy: 0.0000e+00
Epoch 10/300
1/1 [==============================] - 0s 4ms/step - loss: 0.7839 - accuracy

In [7]:
guess = model.predict(test_x.values)
guess

1/1 [==============================] - 0s 141ms/step


array([[ 0.7500581],
       [ 0.7697783],
       [-1.7955719]], dtype=float32)

In [8]:
desnormalizar = test_x.copy()
desnormalizar['Nu'] = guess
desnormalizar

A         E         N        Nu
9  -0.845154 -1.224745  0.000000  0.750058
10 -0.845154  0.000000 -1.224745  0.769778
11  1.183216  1.224745  1.224745 -1.795572

In [9]:
desnormalizado_teste = standardscaler.inverse_transform(desnormalizar)
desnormalizado_teste

array([[25.        ,  1.        ,  8.        , 96.04027931],
       [25.        ,  2.        ,  5.        , 96.50474895],
       [35.        ,  3.        , 11.        , 36.08307582]])

In [10]:
desnormalizar = test_x.copy()
desnormalizar['Nu'] = test_y
desnormalizar

A         E         N        Nu
9  -0.845154 -1.224745  0.000000  0.847698
10 -0.845154  0.000000 -1.224745  0.477469
11  1.183216  1.224745  1.224745 -1.991431

In [11]:
desnormalizado_resultado = standardscaler.inverse_transform(desnormalizar)
desnormalizado_resultado

array([[25.  ,  1.  ,  8.  , 98.34],
       [25.  ,  2.  ,  5.  , 89.62],
       [35.  ,  3.  , 11.  , 31.47]])

In [12]:
scores(desnormalizado_resultado[:,-1],desnormalizado_teste[:,-1])

r2: 0.9720134647717379 meansquarederror: 24.656317271847396 meanabsoluteerror: 4.599181818092923 maxerror: 6.8847489451494965


(0.9720134647717379, 24.656317271847396, 4.599181818092923, 6.8847489451494965)