In [1]:
import pandas as pd
database = pd.read_excel('database_TCC.xlsx')
database = database[['A','E','N','Tmax']]
database

A  E   N    Tmax
0   25  1  11   67.67
1   25  1   5  126.85
2   25  2   8   72.71
3   25  3  11  162.85
4   25  3   5   94.85
5   35  1   8   61.15
6   35  2  11   63.03
7   35  2   5   77.35
8   35  3   8   63.25
9   25  1   8   76.30
10  25  2   5   98.76
11  35  3  11   94.70

In [2]:
from sklearn.preprocessing import StandardScaler
standardscaler = StandardScaler()
standardscaler.fit(database)
data = standardscaler.transform(database)
database = pd.DataFrame(data,columns=database.columns)

In [3]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,max_error

def split_x_and_y(database,x,y):
  dataset_x = database[x]
  dataset_y = database[y]
  return dataset_x,dataset_y


def scores(Y_true, Y_predicted):
  r2 = r2_score(Y_true, Y_predicted)
  meansquarederror = mean_squared_error(Y_true, Y_predicted)
  meanabsoluteerror = mean_absolute_error(Y_true, Y_predicted)
  maxerror = max_error(Y_true, Y_predicted)

  print('r2:',r2,'meansquarederror:',meansquarederror,'meanabsoluteerror:',meanabsoluteerror,'maxerror:',maxerror)
  return r2,meansquarederror,meanabsoluteerror,maxerror


# Random Forest Regressor

In [4]:
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')

In [5]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(dataset_x,dataset_y)

0.8342861330829303

In [6]:
# database.iloc[[0,2,4,5,7,8]]

dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(test_x,test_y)

0.6983549982813197

In [7]:
print(RFR.predict(X = test_x))
print(test_y)

[-0.10245767  0.39924701  0.28871631]
9    -0.411774
10    0.359626
11    0.220183
Name: Tmax, dtype: float64


# SVM

In [8]:
from sklearn import svm
regr = svm.SVR()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
regr.fit(dataset_x,dataset_y)
regr.score(dataset_x,dataset_y)

0.6195483027312697

In [9]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn import svm
regr = svm.SVR()
regr.fit(dataset_x,dataset_y)
regr.score(test_x,test_y)

-0.6642206122135585

# Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
LR.fit(dataset_x,dataset_y)
LR.score(dataset_x,dataset_y)

0.38788075648747644

In [11]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(dataset_x,dataset_y)
LR.score(test_x,test_y)

-1.4847075093225235

# SGD

In [14]:
from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
SGD.fit(dataset_x,dataset_y)
SGD.score(dataset_x,dataset_y)

0.3498448241678096

In [15]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
SGD.fit(dataset_x,dataset_y)
SGD.score(test_x,test_y)

-0.7712996868222046

# BayesianRidge

In [19]:
from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
bayesian.fit(dataset_x,dataset_y)
bayesian.score(dataset_x,dataset_y)

0.24011573474862025

In [20]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
bayesian.fit(dataset_x,dataset_y)
bayesian.score(test_x,test_y)

-0.11081781340792429

# MLP

In [21]:
from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor(max_iter=1000)
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
MLP.fit(dataset_x,dataset_y)
MLP.score(dataset_x,dataset_y)

0.9942359828807333

In [24]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor(max_iter=1000)
MLP.fit(dataset_x,dataset_y)
MLP.score(test_x,test_y)

0.6823247327121325

# Polynomial and Linear

In [25]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(2)
LR = LinearRegression()

dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')

dataset_x_transformed = poly.fit_transform(dataset_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(dataset_x_transformed,dataset_y)

0.9887947794348647

In [1]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(5)
LR = LinearRegression()

dataset_x_transformed = poly.fit_transform(dataset_x)
test_x_transformed = poly.fit_transform(test_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(test_x_transformed,test_y)

NameError: name 'split_x_and_y' is not defined

# Ridge

In [34]:
from sklearn.linear_model import Ridge
ridge = Ridge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Tmax')
ridge.fit(dataset_x,dataset_y)
ridge.score(dataset_x,dataset_y)

0.38436590454105013

In [35]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(dataset_x,dataset_y)
ridge.score(test_x,test_y)

-1.1902408075718736

# Keras

In [36]:
variables,results = split_x_and_y(database,['A','E','N'],'Tmax')
variables.values.shape

(12, 3)

In [37]:
import tensorflow as tf
from tensorflow import keras
# from tensorflow.python.keras.layers import Dense
import pandas as pd
from tensorflow.keras import layers

import keras
from keras.models import Sequential
from keras.layers import Dense

variables,results = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Tmax')
test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Tmax')

model = keras.Sequential([
  layers.Dense(64, activation='sigmoid', input_shape=[len(variables.keys())]),
  # layers.Dropout(0.1),
  layers.Dense(128, activation='sigmoid'),
  layers.Dense(64, activation='sigmoid'),
  layers.Dense(16, activation='sigmoid'),
  layers.Dense(8, activation='sigmoid'),
  # layers.Dense(8, activation='relu'),
  layers.Dense(1)
])

# optimizer = tf.keras.optimizers.RMSprop(0.001)

model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

model.fit(variables.values,results.values,epochs=300)

Epoch 1/300
1/1 [==============================] - 1s 557ms/step - loss: 2.1789 - accuracy: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 5ms/step - loss: 2.1249 - accuracy: 0.0000e+00
Epoch 3/300
1/1 [==============================] - 0s 5ms/step - loss: 2.0728 - accuracy: 0.0000e+00
Epoch 4/300
1/1 [==============================] - 0s 5ms/step - loss: 2.0227 - accuracy: 0.0000e+00
Epoch 5/300
1/1 [==============================] - 0s 6ms/step - loss: 1.9747 - accuracy: 0.0000e+00
Epoch 6/300
1/1 [==============================] - 0s 6ms/step - loss: 1.9290 - accuracy: 0.0000e+00
Epoch 7/300
1/1 [==============================] - 0s 6ms/step - loss: 1.8856 - accuracy: 0.0000e+00
Epoch 8/300
1/1 [==============================] - 0s 5ms/step - loss: 1.8445 - accuracy: 0.0000e+00
Epoch 9/300
1/1 [==============================] - 0s 5ms/step - loss: 1.8057 - accuracy: 0.0000e+00
Epoch 10/300
1/1 [==============================] - 0s 4ms/step - loss: 1.7692 - accuracy

In [38]:
guess = model.predict(test_x.values)
guess

1/1 [==============================] - 0s 83ms/step


array([[-0.02458519],
       [-0.01972732],
       [-0.02600938]], dtype=float32)

In [39]:
desnormalizar = test_x.copy()
desnormalizar['Tmax'] = guess
desnormalizar

A         E         N      Tmax
9  -0.845154 -1.224745  0.000000 -0.024585
10 -0.845154  0.000000 -1.224745 -0.019727
11  1.183216  1.224745  1.224745 -0.026009

In [40]:
desnormalizado_teste = standardscaler.inverse_transform(desnormalizar)
desnormalizado_teste

array([[25.        ,  1.        ,  8.        , 87.57334697],
       [25.        ,  2.        ,  5.        , 87.71478813],
       [35.        ,  3.        , 11.        , 87.5318803 ]])

In [41]:
desnormalizar = test_x.copy()
desnormalizar['Tmax'] = test_y
desnormalizar

A         E         N      Tmax
9  -0.845154 -1.224745  0.000000 -0.411774
10 -0.845154  0.000000 -1.224745  0.359626
11  1.183216  1.224745  1.224745  0.220183

In [42]:
desnormalizado_resultado = standardscaler.inverse_transform(desnormalizar)
desnormalizado_resultado

array([[25.  ,  1.  ,  8.  , 76.3 ],
       [25.  ,  2.  ,  5.  , 98.76],
       [35.  ,  3.  , 11.  , 94.7 ]])

In [43]:
scores(desnormalizado_resultado[:,-1],desnormalizado_teste[:,-1])

r2: -0.048756282771498904 meansquarederror: 100.15566566799407 meanabsoluteerror: 9.828892843458997 maxerror: 11.273346966219052


(-0.048756282771498904,
 100.15566566799407,
 9.828892843458997,
 11.273346966219052)