In [3]:
import pandas as pd
database = pd.read_excel('database_TCC.xlsx')
database = database[['A','E','N','Rt']]
database

A  E   N     Rt
0   25  1  11  1.638
1   25  1   5  2.595
2   25  2   8  1.976
3   25  3  11  4.164
4   25  3   5  2.869
5   35  1   8  1.421
6   35  2  11  1.564
7   35  2   5  2.101
8   35  3   8  1.591
9   25  1   8  1.946
10  25  2   5  2.991
11  35  3  11  2.896

In [4]:
from sklearn.preprocessing import StandardScaler
standardscaler = StandardScaler()
standardscaler.fit(database)
data = standardscaler.transform(database)
database = pd.DataFrame(data,columns=database.columns)

In [5]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,max_error

def split_x_and_y(database,x,y):
  dataset_x = database[x]
  dataset_y = database[y]
  return dataset_x,dataset_y


def scores(Y_true, Y_predicted):
  r2 = r2_score(Y_true, Y_predicted)
  meansquarederror = mean_squared_error(Y_true, Y_predicted)
  meanabsoluteerror = mean_absolute_error(Y_true, Y_predicted)
  maxerror = max_error(Y_true, Y_predicted)

  print('r2:',r2,'meansquarederror:',meansquarederror,'meanabsoluteerror:',meanabsoluteerror,'maxerror:',maxerror)
  return r2,meansquarederror,meanabsoluteerror,maxerror


# Random Forest Regressor

In [6]:
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')

In [7]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(dataset_x,dataset_y)

0.8832211469208688

In [8]:
# database.iloc[[0,2,4,5,7,8]]

dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=1000)
RFR.fit(dataset_x,dataset_y)
RFR.score(test_x,test_y)

0.2890939594804205

In [9]:
print(RFR.predict(X = test_x))
print(test_y)

[-0.46632199  0.09000826  0.33460856]
9    -0.472016
10    0.873229
11    0.750934
Name: Rt, dtype: float64


# SVM

In [10]:
from sklearn import svm
regr = svm.SVR()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
regr.fit(dataset_x,dataset_y)
regr.score(dataset_x,dataset_y)

0.6652552209232103

In [11]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn import svm
regr = svm.SVR()
regr.fit(dataset_x,dataset_y)
regr.score(test_x,test_y)

-0.8498515390854082

# Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
LR.fit(dataset_x,dataset_y)
LR.score(dataset_x,dataset_y)

0.5695908689603328

In [13]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(dataset_x,dataset_y)
LR.score(test_x,test_y)

-0.08386801635430441

# SGD

In [14]:
from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
SGD.fit(dataset_x,dataset_y)
SGD.score(dataset_x,dataset_y)

0.528407588315263

In [15]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.linear_model import SGDRegressor
SGD = SGDRegressor()
SGD.fit(dataset_x,dataset_y)
SGD.score(test_x,test_y)

-0.1395375699193988

# BayesianRidge

In [16]:
from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
bayesian.fit(dataset_x,dataset_y)
bayesian.score(dataset_x,dataset_y)

0.5286310907728824

In [17]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.linear_model import BayesianRidge
bayesian = BayesianRidge()
bayesian.fit(dataset_x,dataset_y)
bayesian.score(test_x,test_y)

-0.2350156608473719

# MLP

In [18]:
from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor(max_iter=1000)
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
MLP.fit(dataset_x,dataset_y)
MLP.score(dataset_x,dataset_y)

0.9896211893559368

In [19]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.neural_network import MLPRegressor
MLP = MLPRegressor(max_iter=1000)
MLP.fit(dataset_x,dataset_y)
MLP.score(test_x,test_y)

0.11597948956103554

# Polynomial and Linear

In [20]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(2)
LR = LinearRegression()

dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')

dataset_x_transformed = poly.fit_transform(dataset_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(dataset_x_transformed,dataset_y)

0.9543474864060848

In [44]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(2)
LR = LinearRegression()

dataset_x_transformed = poly.fit_transform(dataset_x)
test_x_transformed = poly.fit_transform(test_x)

LR.fit(dataset_x_transformed,dataset_y)
LR.score(test_x_transformed,test_y)

0.07291457662648648

# Ridge

In [28]:
from sklearn.linear_model import Ridge
ridge = Ridge()
dataset_x,dataset_y = split_x_and_y(database,['A','E','N'],'Rt')
ridge.fit(dataset_x,dataset_y)
ridge.score(dataset_x,dataset_y)

0.5644440727450447

In [29]:
dataset_x,dataset_y = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')

test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(dataset_x,dataset_y)
ridge.score(test_x,test_y)

-0.11708240725810781

# Keras

In [30]:
variables,results = split_x_and_y(database,['A','E','N'],'Rt')
variables.values.shape

(12, 3)

In [31]:
import tensorflow as tf
from tensorflow import keras
# from tensorflow.python.keras.layers import Dense
import pandas as pd
from tensorflow.keras import layers

import keras
from keras.models import Sequential
from keras.layers import Dense

variables,results = split_x_and_y(database.iloc[[0,1,2,3,4,5,6,7,8]],['A','E','N'],'Rt')
test_x,test_y = split_x_and_y(database.iloc[[9,10,11]],['A','E','N'],'Rt')

model = keras.Sequential([
  layers.Dense(64, activation='sigmoid', input_shape=[len(variables.keys())]),
  # layers.Dropout(0.1),
  layers.Dense(128, activation='sigmoid'),
  layers.Dense(64, activation='sigmoid'),
  layers.Dense(16, activation='sigmoid'),
  layers.Dense(8, activation='sigmoid'),
  # layers.Dense(8, activation='relu'),
  layers.Dense(1)
])

# optimizer = tf.keras.optimizers.RMSprop(0.001)

model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

model.fit(variables.values,results.values,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 427ms/step - loss: 1.2388 - accuracy: 0.0000e+00
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 1.2194 - accuracy: 0.0000e+00
Epoch 3/300
1/1 [==============================] - 0s 4ms/step - loss: 1.2025 - accuracy: 0.0000e+00
Epoch 4/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1880 - accuracy: 0.0000e+00
Epoch 5/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1759 - accuracy: 0.0000e+00
Epoch 6/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1661 - accuracy: 0.0000e+00
Epoch 7/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1584 - accuracy: 0.0000e+00
Epoch 8/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1527 - accuracy: 0.0000e+00
Epoch 9/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1486 - accuracy: 0.0000e+00
Epoch 10/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1460 - accuracy

In [32]:
guess = model.predict(test_x.values)
guess

1/1 [==============================] - 0s 88ms/step


array([[-0.44369394],
       [-0.33617368],
       [-0.62389463]], dtype=float32)

In [33]:
desnormalizar = test_x.copy()
desnormalizar['Tmax'] = guess
desnormalizar

A         E         N      Tmax
9  -0.845154 -1.224745  0.000000 -0.443694
10 -0.845154  0.000000 -1.224745 -0.336174
11  1.183216  1.224745  1.224745 -0.623895

In [34]:
desnormalizado_teste = standardscaler.inverse_transform(desnormalizar)
desnormalizado_teste

array([[25.        ,  1.        ,  8.        ,  1.9680007 ],
       [25.        ,  2.        ,  5.        ,  2.05152353],
       [35.        ,  3.        , 11.        ,  1.82801897]])

In [35]:
desnormalizar = test_x.copy()
desnormalizar['Tmax'] = test_y
desnormalizar

A         E         N      Tmax
9  -0.845154 -1.224745  0.000000 -0.472016
10 -0.845154  0.000000 -1.224745  0.873229
11  1.183216  1.224745  1.224745  0.750934

In [36]:
desnormalizado_resultado = standardscaler.inverse_transform(desnormalizar)
desnormalizado_resultado

array([[25.   ,  1.   ,  8.   ,  1.946],
       [25.   ,  2.   ,  5.   ,  2.991],
       [35.   ,  3.   , 11.   ,  2.896]])

In [37]:
scores(desnormalizado_resultado[:,-1],desnormalizado_teste[:,-1])

r2: -2.030146835225691 meansquarederror: 0.6745611879684926 meanabsoluteerror: 0.6764860692914995 maxerror: 1.0679810345328444


(-2.030146835225691,
 0.6745611879684926,
 0.6764860692914995,
 1.0679810345328444)